### ISSUE TITLE
没有dagger就好了

### ISSUE THREAD

**Issue by dedeTao** [jenly1314/MVVMFrame#1]

**Comment by jenly1314** [comment]
之所以使用Dagger是有原因的，这可能和项目的大小有关，在开发小项目时Dagger可能体现不出其优势，反而感觉代码变得复杂了，但在开发大项目的时候，就越是能体会到Dagger的魅力所在。
1、项目里有相关的[Demo](https://github.com/jenly1314/MVVMFrame/tree/master/app)示例，确实需要至少学习一点Dagger才比较容易上手，虽然框架中使用了Dagger，但如果不是很熟悉Dagger，只需按照[Demo](https://github.com/jenly1314/MVVMFrame/tree/master/app)中相关的配置满足框架规范，在自己项目实现的过程中也可以少用Dagger。
2、Dagger存在一定的学习曲线，相关注解可能没那么通俗易懂，相关的文章也很多，学习是很有必要的。
