### ISSUE TITLE
关于demo的看法

### ISSUE THREAD

**Issue by senjoeson** [jenly1314/MVVMFrame#2]
建议是demo单独搞个项目,最好不要弄在一起, 我们下载源码,发现总是构建失败,嗯 和谷歌的AAC一样, 结果可能就是放弃使用```你的框架, @jenly1314

**Comment by jenly1314** [comment]
构建失败是什么意思?没太理解你的意思，构建失败应该有个原因吧。（如 ：Gradle版本问题，引入依赖失败，引入依赖版本不一致，DataBinding文件未生成，Dagger文件未生成，少了某个步骤或配置等等），具体原因具体分析。这个和一个Project多个module好像没什么关系。
PS:一个项目引入第三方库一般推荐以Gradle的方式引入比较好，方便维护和更新。只有在这个库满足不了你的需求，而妥协以module的方式引入，因为在未熟知这个库的情况下，手动改动存在不可预知的风险。

**Comment by senjoeson** [comment]
xercesImpl-2.9.1.jar一直无法下载下来

**Comment by senjoeson** [comment]
我的意思是把一个demo 也这样写 虽然规范是规范了 但是也增加了阅读难度,还有当我构建失败的时候,想复制你的demo到我的项目,会发现 很多依赖还得一个个找,然后复制过去,这样很麻烦,
![image](https://user-images.githubusercontent.com/24454887/59487026-ed1b8180-8ead-11e9-851c-db2741f62e45.png)

以下就是构建报错, 
![image](https://user-images.githubusercontent.com/24454887/59487062-19370280-8eae-11e9-95fa-66d84d96daac.png)

**Comment by jenly1314** [comment]
所有依赖都放在versions.gradle里面配置，这样方便维护，统一管理。详情请查看[android-architecture-components](https://github.com/googlesamples/android-architecture-components)
你这个xercesImp-2.9.1.jar依赖不下来与MVVMFrame没有任何关系 ，导致的原因是jcenter仓库本身没有这个库，添加其它仓库地址吧。如：mavenCentral()
