### ISSUE TITLE
请教下repository该如何被注入到应用里

### ISSUE THREAD

**Issue by zijianwang90** [jenly1314/MVVMFrame#4]
我在看demo中都弱化了repository这一层，那如果我想要在viewmodel中使用repository的话（继承自DataRepository），请问该如何在dagger中正确的注入该repository呢？

**Comment by jenly1314** [comment]
本库中的Repository与常规的MVVM写法上确实弱化了，DataRepository是Repository一个实现类。这里的Repository主要是为提供远程数据和本地数据作为一个中间桥梁。但本质并没有变，你可以直接在Model层通过getRetrofitService获取定义的接口来操作远程数据或通过getRoomDatabase来操作本地数据库。实际需求场景，根据具体需求而定，如果是很简单的，你还可以继续弱化Model层，通过DataViewModel获取定义的接口。这些在[App demo](https://github.com/jenly1314/MVVMFrame/tree/master/app)中都有相关示例。项目中的 [example module](https://github.com/jenly1314/MVVMFrame/tree/master/example) 是一个所有集成步骤和依赖注入都写好了空模板示例。[README](https://github.com/jenly1314/MVVMFrame/blob/master/README.md#%E7%9B%B8%E5%85%B3%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE)中也有相关的开源项目使用示例都可以参考。
