### ISSUE TITLE
如果是实现模块化和组件化，是不是每个模块都有一个application的继承类

### ISSUE THREAD

**Issue by Penny7088** [jenly1314/MVVMFrame#5]

**Comment by jenly1314** [comment]
* 需不需要每个 **module** 都有一个 **Application** 的继承类，取决于你的模块架构设计。你可以将 **MVVMFrame** 作为公共模块的基础架构。
* 当  **module** 为 **application** 时，你可以每个子模块都使用公共模块中定义的 **Application** 来初始化，也可以每个子模块都有一个自定义的 **Application** 来初始化。
* 当 **module** 为 **library** 时，你可以使用 **公共模块** 或 **主app** 中定义的 **Application** 来初始化各个子模块。
* 总结：上面所说的都是具有片面性的，需要综合起来看。因为当 **module** 作为独立模块运行和作为子模块依赖 **主App** 时，这其中的核心问题在于怎么去统一管理。个人建议通过 **接口反射** 的方式统一管理各个 **module**  的初始化。这样各个 **module** 在 **application** 与 **library** 之间切换时，便于管理。

**Comment by Penny7088** [comment]
我只直接在空app里面初始化操作的。后续再修改
