### ISSUE TITLE
折叠屏，或者旋转会导致model为空

### ISSUE THREAD

**Issue by zt174499006** [jenly1314/MVVMFrame#6]
class GroupChatViewModel @Inject constructor(application: Application, model: GroupChatModel?) :
    MessageViewModel<GroupChatModel>(application, model) {

model对象事空的，只需要屏幕旋转就会空，首次，只要不旋转，对象就没问题

**Comment by jenly1314** [comment]
[EasyChatAndroidClient#5](https://github.com/yetel/EasyChatAndroidClient/issues/5)
